/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type PaymentWebhook = {
  _id: string;
  _type: "paymentWebhook";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  provider?: "giselpay" | "kpay" | "cryptomus" | "coinbase" | "unknown";
  payload?: string;
  receivedAt?: string;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleFr?: string;
  href?: string;
  icon?: string;
  isExternal?: boolean;
  order?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: string;
  siteDescription?: string;
  siteKeywords?: Array<string>;
  siteLogo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  favicon?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  primaryColor?: string;
  secondaryColor?: string;
  accentColor?: string;
  ctaText?: string;
  ctaUrl?: string;
  heroHeadline?: string;
  heroSubheadline?: string;
  heroBackground?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  showBlog?: boolean;
  showServices?: boolean;
  showTestimonials?: boolean;
  googleAnalyticsId?: string;
  facebookPixelId?: string;
  twitterHandle?: string;
  footer?: {
    text?: string;
    copyrightText?: string;
    links?: Array<{
      title?: string;
      url?: string;
      _key: string;
    }>;
  };
  maintenanceMode?: boolean;
  maintenanceMessage?: string;
};

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  subject?: string;
  message?: string;
  submittedAt?: string;
  status?: "new" | "archived";
  notes?: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleFr?: string;
  slug?: Slug;
  icon?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  shortDescription?: string;
  shortDescriptionFr?: string;
  fullDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  fullDescriptionFr?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  features?: Array<string>;
  featuresFr?: Array<string>;
  technologies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
  deliverables?: Array<string>;
  deliverablesFr?: Array<string>;
  pricing?: {
    priceType?: "hourly" | "project" | "monthly" | "custom";
    visible?: boolean;
  };
  internationalPrice?: number;
  internationalCurrency?: string;
  localPrice?: number;
  localCurrency?: "XAF" | "XOF" | "NGN" | "GHS" | "KES" | "ZAR" | "RWF" | "UGX";
  localDiscountPercent?: number;
  pricingDescription?: string;
  timeline?: string;
  documentation?: Array<string>;
  documentationFr?: Array<string>;
  workflow?: Array<string>;
  workflowFr?: Array<string>;
  featured?: boolean;
  order?: number;
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleFr?: string;
  slug?: Slug;
  excerpt?: string;
  excerptFr?: string;
  featuredImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  category?:
    | "tutorial"
    | "technical"
    | "ai-ml"
    | "web-dev"
    | "career"
    | "opinion"
    | "showcase"
    | "best-practices"
    | "news";
  tags?: Array<string>;
  publishedAt?: string;
  readTime?: number;
};

export type Achievement = {
  _id: string;
  _type: "achievement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleFr?: string;
  type?:
    | "award"
    | "hackathon"
    | "publication"
    | "speaking"
    | "open-source"
    | "milestone"
    | "recognition"
    | "other";
  issuer?: string;
  date?: string;
  description?: string;
  descriptionFr?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url?: string;
  featured?: boolean;
  order?: number;
};

export type Certification = {
  _id: string;
  _type: "certification";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  nameFr?: string;
  issuer?: string;
  recipientName?: string;
  issueDate?: string;
  expiryDate?: string;
  credentialId?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  certificateFile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  certificateImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  credentialUrl?: string;
  description?: string;
  descriptionFr?: string;
  skills?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
  order?: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  position?: string;
  company?: string;
  avatar?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  testimonial?: string;
  testimonialFr?: string;
  rating?: number;
  date?: string;
  linkedinUrl?: string;
  companyLogo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  featured?: boolean;
  order?: number;
};

export type Education = {
  _id: string;
  _type: "education";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  institution?: string;
  degree?: string;
  degreeFr?: string;
  fieldOfStudy?: string;
  fieldOfStudyFr?: string;
  startDate?: string;
  endDate?: string;
  current?: boolean;
  gpa?: string;
  description?: string;
  descriptionFr?: string;
  achievements?: Array<string>;
  achievementsFr?: Array<string>;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  website?: string;
  order?: number;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company?: string;
  position?: string;
  positionFr?: string;
  employmentType?:
    | "full-time"
    | "part-time"
    | "contract"
    | "freelance"
    | "internship";
  location?: string;
  startDate?: string;
  endDate?: string;
  current?: boolean;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  descriptionFr?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  responsibilities?: Array<string>;
  responsibilitiesFr?: Array<string>;
  achievements?: Array<string>;
  achievementsFr?: Array<string>;
  technologies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
  companyLogo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  companyWebsite?: string;
  order?: number;
};

export type Skill = {
  _id: string;
  _type: "skill";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  category?:
    | "frontend"
    | "backend"
    | "ai-ml"
    | "data"
    | "devops"
    | "cloud"
    | "database"
    | "mobile"
    | "testing"
    | "design"
    | "network"
    | "security"
    | "marketing"
    | "tools"
    | "soft-skills"
    | "other";
  proficiency?: "beginner" | "intermediate" | "advanced" | "expert";
  percentage?: number;
  yearsOfExperience?: number;
  color?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleFr?: string;
  slug?: Slug;
  tagline?: string;
  taglineFr?: string;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  technologies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
  category?:
    | "web-app"
    | "mobile-app"
    | "ai-ml"
    | "api-backend"
    | "devops"
    | "open-source"
    | "cli-tool"
    | "desktop-app"
    | "browser-extension"
    | "game"
    | "other";
  liveUrl?: string;
  githubUrl?: string;
  featured?: boolean;
  order?: number;
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName?: string;
  lastName?: string;
  headline?: string;
  headlineFr?: string;
  headlineStaticText?: string;
  headlineStaticTextFr?: string;
  headlineAnimatedWords?: Array<string>;
  headlineAnimatedWordsFr?: Array<string>;
  headlineAnimationDuration?: number;
  shortBio?: string;
  shortBioFr?: string;
  fullBio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  fullBioFr?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  profileImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  email?: string;
  emailProfessional?: string;
  phone?: string;
  phoneSecondary?: string;
  whatsapp?: string;
  location?: string;
  resumeUrl?: string;
  availability?: "available" | "open" | "unavailable";
  profession?: string;
  professionFr?: string;
  expertiseDomains?: Array<string>;
  socialLinks?: Array<{
    platform?:
      | "website"
      | "email"
      | "phone"
      | "github"
      | "gitlab"
      | "bitbucket"
      | "linkedin"
      | "x"
      | "twitter"
      | "facebook"
      | "instagram"
      | "youtube"
      | "tiktok"
      | "snapchat"
      | "threads"
      | "bluesky"
      | "mastodon"
      | "reddit"
      | "discord"
      | "telegram"
      | "whatsapp"
      | "twitch"
      | "vk"
      | "weibo"
      | "tumblr"
      | "flickr"
      | "vimeo"
      | "soundcloud"
      | "spotify"
      | "applepodcast"
      | "googlepodcasts"
      | "patreon"
      | "producthunt"
      | "medium"
      | "stackoverflow"
      | "codepen"
      | "codesandbox"
      | "hackerrank"
      | "leetcode"
      | "behance"
      | "dribbble"
      | "figma"
      | "pinterest"
      | "appstore"
      | "googleplay"
      | "linktree"
      | "huggingface";
    url?: string;
    label?: string;
    showInContact?: boolean;
    enabled?: boolean;
    _type: "socialLink";
    _key: string;
  }>;
  yearsOfExperience?: number;
  stats?: Array<{
    label?: string;
    labelFr?: string;
    value?: string;
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | PaymentWebhook
  | Navigation
  | SiteSettings
  | Contact
  | Service
  | Blog
  | Achievement
  | Certification
  | Testimonial
  | Education
  | Experience
  | Skill
  | Project
  | Profile
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./app/request/page.tsx
// Variable: SERVICE_QUERY
// Query: *[_type == "service" && slug.current == $slug][0]{  title,  titleFr,  shortDescription,  shortDescriptionFr,  pricing,  internationalPrice,  internationalCurrency,  localPrice,  localCurrency,  localDiscountPercent,  pricingDescription,  deliverables,  deliverablesFr,  workflow,  workflowFr,  timeline}
export type SERVICE_QUERYResult = {
  title: string | null;
  titleFr: string | null;
  shortDescription: string | null;
  shortDescriptionFr: string | null;
  pricing: {
    priceType?: "custom" | "hourly" | "monthly" | "project";
    visible?: boolean;
  } | null;
  internationalPrice: number | null;
  internationalCurrency: string | null;
  localPrice: number | null;
  localCurrency:
    | "GHS"
    | "KES"
    | "NGN"
    | "RWF"
    | "UGX"
    | "XAF"
    | "XOF"
    | "ZAR"
    | null;
  localDiscountPercent: number | null;
  pricingDescription: string | null;
  deliverables: Array<string> | null;
  deliverablesFr: Array<string> | null;
  workflow: Array<string> | null;
  workflowFr: Array<string> | null;
  timeline: string | null;
} | null;

// Source: ./components/FloatingDock.tsx
// Variable: NAVIGATION_QUERY
// Query: *[_type == "navigation"] | order(order asc){  title,  titleFr,  href,  icon,  isExternal}
export type NAVIGATION_QUERYResult = Array<{
  title: string | null;
  titleFr: string | null;
  href: string | null;
  icon: string | null;
  isExternal: boolean | null;
}>;

// Source: ./components/chat/ChatWrapper.tsx
// Variable: CHAT_PROFILE_QUERY
// Query: *[_id == "singleton-profile"][0]{    _id,    _type,    firstName,    lastName,    headline,    shortBio,    email,    phone,    location,    availability,    yearsOfExperience,    profileImage  }
export type CHAT_PROFILE_QUERYResult =
  | {
      _id: string;
      _type: "achievement";
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: string;
      _type: "blog";
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: string;
      _type: "certification";
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: string;
      _type: "contact";
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: string | null;
      phone: null;
      location: null;
      availability: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: string;
      _type: "education";
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: string;
      _type: "experience";
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: string | null;
      availability: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: string;
      _type: "navigation";
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: string;
      _type: "paymentWebhook";
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: string;
      _type: "profile";
      firstName: string | null;
      lastName: string | null;
      headline: string | null;
      shortBio: string | null;
      email: string | null;
      phone: string | null;
      location: string | null;
      availability: "available" | "open" | "unavailable" | null;
      yearsOfExperience: number | null;
      profileImage: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
    }
  | {
      _id: string;
      _type: "project";
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: string;
      _type: "sanity.fileAsset";
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: string;
      _type: "sanity.imageAsset";
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: string;
      _type: "service";
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: string;
      _type: "siteSettings";
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      _id: string;
      _type: "skill";
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      yearsOfExperience: number | null;
      profileImage: null;
    }
  | {
      _id: string;
      _type: "testimonial";
      firstName: null;
      lastName: null;
      headline: null;
      shortBio: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | null;

// Source: ./components/sections/AboutSection.tsx
// Variable: ABOUT_QUERY
// Query: *[_id == "singleton-profile"][0]{  firstName,  lastName,  fullBio,  fullBioFr,  yearsOfExperience,  stats,  email,  phone,  location}
export type ABOUT_QUERYResult =
  | {
      firstName: null;
      lastName: null;
      fullBio: null;
      fullBioFr: null;
      yearsOfExperience: null;
      stats: null;
      email: null;
      phone: null;
      location: null;
    }
  | {
      firstName: null;
      lastName: null;
      fullBio: null;
      fullBioFr: null;
      yearsOfExperience: number | null;
      stats: null;
      email: null;
      phone: null;
      location: null;
    }
  | {
      firstName: null;
      lastName: null;
      fullBio: null;
      fullBioFr: null;
      yearsOfExperience: null;
      stats: null;
      email: null;
      phone: null;
      location: string | null;
    }
  | {
      firstName: null;
      lastName: null;
      fullBio: null;
      fullBioFr: null;
      yearsOfExperience: null;
      stats: null;
      email: string | null;
      phone: null;
      location: null;
    }
  | {
      firstName: string | null;
      lastName: string | null;
      fullBio: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      fullBioFr: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }> | null;
      yearsOfExperience: number | null;
      stats: Array<{
        label?: string;
        labelFr?: string;
        value?: string;
        _key: string;
      }> | null;
      email: string | null;
      phone: string | null;
      location: string | null;
    }
  | null;

// Source: ./components/sections/AchievementsSection.tsx
// Variable: ACHIEVEMENTS_QUERY
// Query: *[_type == "achievement"] | order(date desc){  title,  titleFr,  type,  issuer,  date,  description,  descriptionFr,  image,  url,  featured,  order}
export type ACHIEVEMENTS_QUERYResult = Array<{
  title: string | null;
  titleFr: string | null;
  type:
    | "award"
    | "hackathon"
    | "milestone"
    | "open-source"
    | "other"
    | "publication"
    | "recognition"
    | "speaking"
    | null;
  issuer: string | null;
  date: string | null;
  description: string | null;
  descriptionFr: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  url: string | null;
  featured: boolean | null;
  order: number | null;
}>;

// Source: ./components/sections/BlogSection.tsx
// Variable: BLOG_QUERY
// Query: *[_type == "blog"] | order(publishedAt desc){  title,  titleFr,  slug,  excerpt,  excerptFr,  category,  tags,  publishedAt,  readTime,  featuredImage}
export type BLOG_QUERYResult = Array<{
  title: string | null;
  titleFr: string | null;
  slug: Slug | null;
  excerpt: string | null;
  excerptFr: string | null;
  category:
    | "ai-ml"
    | "best-practices"
    | "career"
    | "news"
    | "opinion"
    | "showcase"
    | "technical"
    | "tutorial"
    | "web-dev"
    | null;
  tags: Array<string> | null;
  publishedAt: string | null;
  readTime: number | null;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: ./components/sections/CertificationsSection.tsx
// Variable: CERTIFICATIONS_QUERY
// Query: *[_type == "certification"] | order(order asc){  name,  nameFr,  issuer,  recipientName,  issueDate,  expiryDate,  credentialId,  credentialUrl,  logo,  certificateFile{asset->{url,_id}},  certificateImage,  description,  descriptionFr,  skills[]->{name, category},  order}
export type CERTIFICATIONS_QUERYResult = Array<{
  name: string | null;
  nameFr: string | null;
  issuer: string | null;
  recipientName: string | null;
  issueDate: string | null;
  expiryDate: string | null;
  credentialId: string | null;
  credentialUrl: string | null;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  certificateFile: {
    asset: {
      url: string | null;
      _id: string;
    } | null;
  } | null;
  certificateImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: string | null;
  descriptionFr: string | null;
  skills: Array<{
    name: string | null;
    category:
      | "ai-ml"
      | "backend"
      | "cloud"
      | "data"
      | "database"
      | "design"
      | "devops"
      | "frontend"
      | "marketing"
      | "mobile"
      | "network"
      | "other"
      | "security"
      | "soft-skills"
      | "testing"
      | "tools"
      | null;
  }> | null;
  order: number | null;
}>;

// Source: ./components/sections/ContactSection.tsx
// Variable: PROFILE_QUERY
// Query: *[_id == "singleton-profile"][0]{  email,  emailProfessional,  phone,  phoneSecondary,  whatsapp,  location,  socialLinks}
export type PROFILE_QUERYResult =
  | {
      email: null;
      emailProfessional: null;
      phone: null;
      phoneSecondary: null;
      whatsapp: null;
      location: null;
      socialLinks: null;
    }
  | {
      email: null;
      emailProfessional: null;
      phone: null;
      phoneSecondary: null;
      whatsapp: null;
      location: string | null;
      socialLinks: null;
    }
  | {
      email: string | null;
      emailProfessional: null;
      phone: null;
      phoneSecondary: null;
      whatsapp: null;
      location: null;
      socialLinks: null;
    }
  | {
      email: string | null;
      emailProfessional: string | null;
      phone: string | null;
      phoneSecondary: string | null;
      whatsapp: string | null;
      location: string | null;
      socialLinks: Array<{
        platform?:
          | "applepodcast"
          | "appstore"
          | "behance"
          | "bitbucket"
          | "bluesky"
          | "codepen"
          | "codesandbox"
          | "discord"
          | "dribbble"
          | "email"
          | "facebook"
          | "figma"
          | "flickr"
          | "github"
          | "gitlab"
          | "googleplay"
          | "googlepodcasts"
          | "hackerrank"
          | "huggingface"
          | "instagram"
          | "leetcode"
          | "linkedin"
          | "linktree"
          | "mastodon"
          | "medium"
          | "patreon"
          | "phone"
          | "pinterest"
          | "producthunt"
          | "reddit"
          | "snapchat"
          | "soundcloud"
          | "spotify"
          | "stackoverflow"
          | "telegram"
          | "threads"
          | "tiktok"
          | "tumblr"
          | "twitch"
          | "twitter"
          | "vimeo"
          | "vk"
          | "website"
          | "weibo"
          | "whatsapp"
          | "x"
          | "youtube";
        url?: string;
        label?: string;
        showInContact?: boolean;
        enabled?: boolean;
        _type: "socialLink";
        _key: string;
      }> | null;
    }
  | null;

// Source: ./components/sections/EducationSection.tsx
// Variable: EDUCATION_QUERY
// Query: *[_type == "education"] | order(endDate desc, startDate desc){  institution,  degree,  degreeFr,  fieldOfStudy,  fieldOfStudyFr,  startDate,  endDate,  current,  gpa,  description,  descriptionFr,  achievements,  achievementsFr,  logo,  website,  order}
export type EDUCATION_QUERYResult = Array<{
  institution: string | null;
  degree: string | null;
  degreeFr: string | null;
  fieldOfStudy: string | null;
  fieldOfStudyFr: string | null;
  startDate: string | null;
  endDate: string | null;
  current: boolean | null;
  gpa: string | null;
  description: string | null;
  descriptionFr: string | null;
  achievements: Array<string> | null;
  achievementsFr: Array<string> | null;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  website: string | null;
  order: number | null;
}>;

// Source: ./components/sections/ExperienceSection.tsx
// Variable: EXPERIENCE_QUERY
// Query: *[_type == "experience"] | order(startDate desc){  company,  position,  positionFr,  employmentType,  location,  startDate,  endDate,  current,  description,  descriptionFr,  responsibilities,  responsibilitiesFr,  achievements,  achievementsFr,  technologies[]->{name, category},  companyLogo,  companyWebsite}
export type EXPERIENCE_QUERYResult = Array<{
  company: string | null;
  position: string | null;
  positionFr: string | null;
  employmentType:
    | "contract"
    | "freelance"
    | "full-time"
    | "internship"
    | "part-time"
    | null;
  location: string | null;
  startDate: string | null;
  endDate: string | null;
  current: boolean | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  descriptionFr: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  responsibilities: Array<string> | null;
  responsibilitiesFr: Array<string> | null;
  achievements: Array<string> | null;
  achievementsFr: Array<string> | null;
  technologies: Array<{
    name: string | null;
    category:
      | "ai-ml"
      | "backend"
      | "cloud"
      | "data"
      | "database"
      | "design"
      | "devops"
      | "frontend"
      | "marketing"
      | "mobile"
      | "network"
      | "other"
      | "security"
      | "soft-skills"
      | "testing"
      | "tools"
      | null;
  }> | null;
  companyLogo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  companyWebsite: string | null;
}>;

// Source: ./components/sections/HeroSection.tsx
// Variable: HERO_QUERY
// Query: *[_id == "singleton-profile"][0]{  firstName,  lastName,  headline,  headlineFr,  headlineStaticText,  headlineStaticTextFr,  headlineAnimatedWords,  headlineAnimatedWordsFr,  headlineAnimationDuration,  shortBio,  shortBioFr,  email,  phone,  location,  availability,  socialLinks,  yearsOfExperience,  profileImage}
export type HERO_QUERYResult =
  | {
      firstName: null;
      lastName: null;
      headline: null;
      headlineFr: null;
      headlineStaticText: null;
      headlineStaticTextFr: null;
      headlineAnimatedWords: null;
      headlineAnimatedWordsFr: null;
      headlineAnimationDuration: null;
      shortBio: null;
      shortBioFr: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      firstName: null;
      lastName: null;
      headline: null;
      headlineFr: null;
      headlineStaticText: null;
      headlineStaticTextFr: null;
      headlineAnimatedWords: null;
      headlineAnimatedWordsFr: null;
      headlineAnimationDuration: null;
      shortBio: null;
      shortBioFr: null;
      email: null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: number | null;
      profileImage: null;
    }
  | {
      firstName: null;
      lastName: null;
      headline: null;
      headlineFr: null;
      headlineStaticText: null;
      headlineStaticTextFr: null;
      headlineAnimatedWords: null;
      headlineAnimatedWordsFr: null;
      headlineAnimationDuration: null;
      shortBio: null;
      shortBioFr: null;
      email: null;
      phone: null;
      location: string | null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      firstName: null;
      lastName: null;
      headline: null;
      headlineFr: null;
      headlineStaticText: null;
      headlineStaticTextFr: null;
      headlineAnimatedWords: null;
      headlineAnimatedWordsFr: null;
      headlineAnimationDuration: null;
      shortBio: null;
      shortBioFr: null;
      email: string | null;
      phone: null;
      location: null;
      availability: null;
      socialLinks: null;
      yearsOfExperience: null;
      profileImage: null;
    }
  | {
      firstName: string | null;
      lastName: string | null;
      headline: string | null;
      headlineFr: string | null;
      headlineStaticText: string | null;
      headlineStaticTextFr: string | null;
      headlineAnimatedWords: Array<string> | null;
      headlineAnimatedWordsFr: Array<string> | null;
      headlineAnimationDuration: number | null;
      shortBio: string | null;
      shortBioFr: string | null;
      email: string | null;
      phone: string | null;
      location: string | null;
      availability: "available" | "open" | "unavailable" | null;
      socialLinks: Array<{
        platform?:
          | "applepodcast"
          | "appstore"
          | "behance"
          | "bitbucket"
          | "bluesky"
          | "codepen"
          | "codesandbox"
          | "discord"
          | "dribbble"
          | "email"
          | "facebook"
          | "figma"
          | "flickr"
          | "github"
          | "gitlab"
          | "googleplay"
          | "googlepodcasts"
          | "hackerrank"
          | "huggingface"
          | "instagram"
          | "leetcode"
          | "linkedin"
          | "linktree"
          | "mastodon"
          | "medium"
          | "patreon"
          | "phone"
          | "pinterest"
          | "producthunt"
          | "reddit"
          | "snapchat"
          | "soundcloud"
          | "spotify"
          | "stackoverflow"
          | "telegram"
          | "threads"
          | "tiktok"
          | "tumblr"
          | "twitch"
          | "twitter"
          | "vimeo"
          | "vk"
          | "website"
          | "weibo"
          | "whatsapp"
          | "x"
          | "youtube";
        url?: string;
        label?: string;
        showInContact?: boolean;
        enabled?: boolean;
        _type: "socialLink";
        _key: string;
      }> | null;
      yearsOfExperience: number | null;
      profileImage: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
    }
  | null;

// Source: ./components/sections/ProjectsSection.tsx
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && featured == true] | order(order asc)[0...6]{  title,  titleFr,  slug,  tagline,  taglineFr,  category,  liveUrl,  githubUrl,  coverImage,  technologies[]->{name, category, color}}
export type PROJECTS_QUERYResult = Array<{
  title: string | null;
  titleFr: string | null;
  slug: Slug | null;
  tagline: string | null;
  taglineFr: string | null;
  category:
    | "ai-ml"
    | "api-backend"
    | "browser-extension"
    | "cli-tool"
    | "desktop-app"
    | "devops"
    | "game"
    | "mobile-app"
    | "open-source"
    | "other"
    | "web-app"
    | null;
  liveUrl: string | null;
  githubUrl: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  technologies: Array<{
    name: string | null;
    category:
      | "ai-ml"
      | "backend"
      | "cloud"
      | "data"
      | "database"
      | "design"
      | "devops"
      | "frontend"
      | "marketing"
      | "mobile"
      | "network"
      | "other"
      | "security"
      | "soft-skills"
      | "testing"
      | "tools"
      | null;
    color: string | null;
  }> | null;
}>;

// Source: ./components/sections/ServicesSection.tsx
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(order asc, _createdAt desc){  title,  titleFr,  slug,  icon,  shortDescription,  shortDescriptionFr,  fullDescription,  fullDescriptionFr,  features,  featuresFr,  technologies[]->{name, category},  deliverables,  deliverablesFr,  pricing,  internationalPrice,  internationalCurrency,  localPrice,  localCurrency,  localDiscountPercent,  pricingDescription,  timeline,  featured,  order}
export type SERVICES_QUERYResult = Array<{
  title: string | null;
  titleFr: string | null;
  slug: Slug | null;
  icon: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  shortDescription: string | null;
  shortDescriptionFr: string | null;
  fullDescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  fullDescriptionFr: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  features: Array<string> | null;
  featuresFr: Array<string> | null;
  technologies: Array<{
    name: string | null;
    category:
      | "ai-ml"
      | "backend"
      | "cloud"
      | "data"
      | "database"
      | "design"
      | "devops"
      | "frontend"
      | "marketing"
      | "mobile"
      | "network"
      | "other"
      | "security"
      | "soft-skills"
      | "testing"
      | "tools"
      | null;
  }> | null;
  deliverables: Array<string> | null;
  deliverablesFr: Array<string> | null;
  pricing: {
    priceType?: "custom" | "hourly" | "monthly" | "project";
    visible?: boolean;
  } | null;
  internationalPrice: number | null;
  internationalCurrency: string | null;
  localPrice: number | null;
  localCurrency:
    | "GHS"
    | "KES"
    | "NGN"
    | "RWF"
    | "UGX"
    | "XAF"
    | "XOF"
    | "ZAR"
    | null;
  localDiscountPercent: number | null;
  pricingDescription: string | null;
  timeline: string | null;
  featured: boolean | null;
  order: number | null;
}>;

// Source: ./components/sections/SkillsSection.tsx
// Variable: SKILLS_QUERY
// Query: *[_type == "skill"] | order(category asc, order asc){  name,  category,  proficiency,  percentage,  yearsOfExperience,  color}
export type SKILLS_QUERYResult = Array<{
  name: string | null;
  category:
    | "ai-ml"
    | "backend"
    | "cloud"
    | "data"
    | "database"
    | "design"
    | "devops"
    | "frontend"
    | "marketing"
    | "mobile"
    | "network"
    | "other"
    | "security"
    | "soft-skills"
    | "testing"
    | "tools"
    | null;
  proficiency: "advanced" | "beginner" | "expert" | "intermediate" | null;
  percentage: number | null;
  yearsOfExperience: number | null;
  color: string | null;
}>;

// Source: ./components/sections/TestimonialsSection.tsx
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial" && featured == true] | order(order asc){  name,  position,  company,  testimonial,  testimonialFr,  rating,  date,  avatar,  companyLogo,  linkedinUrl}
export type TESTIMONIALS_QUERYResult = Array<{
  name: string | null;
  position: string | null;
  company: string | null;
  testimonial: string | null;
  testimonialFr: string | null;
  rating: number | null;
  date: string | null;
  avatar: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  companyLogo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  linkedinUrl: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "service" && slug.current == $slug][0]{\n  title,\n  titleFr,\n  shortDescription,\n  shortDescriptionFr,\n  pricing,\n  internationalPrice,\n  internationalCurrency,\n  localPrice,\n  localCurrency,\n  localDiscountPercent,\n  pricingDescription,\n  deliverables,\n  deliverablesFr,\n  workflow,\n  workflowFr,\n  timeline\n}': SERVICE_QUERYResult;
    '*[_type == "navigation"] | order(order asc){\n  title,\n  titleFr,\n  href,\n  icon,\n  isExternal\n}': NAVIGATION_QUERYResult;
    '*[_id == "singleton-profile"][0]{\n    _id,\n    _type,\n    firstName,\n    lastName,\n    headline,\n    shortBio,\n    email,\n    phone,\n    location,\n    availability,\n    yearsOfExperience,\n    profileImage\n  }': CHAT_PROFILE_QUERYResult;
    '*[_id == "singleton-profile"][0]{\n  firstName,\n  lastName,\n  fullBio,\n  fullBioFr,\n  yearsOfExperience,\n  stats,\n  email,\n  phone,\n  location\n}': ABOUT_QUERYResult;
    '*[_type == "achievement"] | order(date desc){\n  title,\n  titleFr,\n  type,\n  issuer,\n  date,\n  description,\n  descriptionFr,\n  image,\n  url,\n  featured,\n  order\n}': ACHIEVEMENTS_QUERYResult;
    '*[_type == "blog"] | order(publishedAt desc){\n  title,\n  titleFr,\n  slug,\n  excerpt,\n  excerptFr,\n  category,\n  tags,\n  publishedAt,\n  readTime,\n  featuredImage\n}': BLOG_QUERYResult;
    '*[_type == "certification"] | order(order asc){\n  name,\n  nameFr,\n  issuer,\n  recipientName,\n  issueDate,\n  expiryDate,\n  credentialId,\n  credentialUrl,\n  logo,\n  certificateFile{asset->{url,_id}},\n  certificateImage,\n  description,\n  descriptionFr,\n  skills[]->{name, category},\n  order\n}': CERTIFICATIONS_QUERYResult;
    '*[_id == "singleton-profile"][0]{\n  email,\n  emailProfessional,\n  phone,\n  phoneSecondary,\n  whatsapp,\n  location,\n  socialLinks\n}': PROFILE_QUERYResult;
    '*[_type == "education"] | order(endDate desc, startDate desc){\n  institution,\n  degree,\n  degreeFr,\n  fieldOfStudy,\n  fieldOfStudyFr,\n  startDate,\n  endDate,\n  current,\n  gpa,\n  description,\n  descriptionFr,\n  achievements,\n  achievementsFr,\n  logo,\n  website,\n  order\n}': EDUCATION_QUERYResult;
    '*[_type == "experience"] | order(startDate desc){\n  company,\n  position,\n  positionFr,\n  employmentType,\n  location,\n  startDate,\n  endDate,\n  current,\n  description,\n  descriptionFr,\n  responsibilities,\n  responsibilitiesFr,\n  achievements,\n  achievementsFr,\n  technologies[]->{name, category},\n  companyLogo,\n  companyWebsite\n}': EXPERIENCE_QUERYResult;
    '*[_id == "singleton-profile"][0]{\n  firstName,\n  lastName,\n  headline,\n  headlineFr,\n  headlineStaticText,\n  headlineStaticTextFr,\n  headlineAnimatedWords,\n  headlineAnimatedWordsFr,\n  headlineAnimationDuration,\n  shortBio,\n  shortBioFr,\n  email,\n  phone,\n  location,\n  availability,\n  socialLinks,\n  yearsOfExperience,\n  profileImage\n}': HERO_QUERYResult;
    '*[_type == "project" && featured == true] | order(order asc)[0...6]{\n  title,\n  titleFr,\n  slug,\n  tagline,\n  taglineFr,\n  category,\n  liveUrl,\n  githubUrl,\n  coverImage,\n  technologies[]->{name, category, color}\n}': PROJECTS_QUERYResult;
    '*[_type == "service"] | order(order asc, _createdAt desc){\n  title,\n  titleFr,\n  slug,\n  icon,\n  shortDescription,\n  shortDescriptionFr,\n  fullDescription,\n  fullDescriptionFr,\n  features,\n  featuresFr,\n  technologies[]->{name, category},\n  deliverables,\n  deliverablesFr,\n  pricing,\n  internationalPrice,\n  internationalCurrency,\n  localPrice,\n  localCurrency,\n  localDiscountPercent,\n  pricingDescription,\n  timeline,\n  featured,\n  order\n}': SERVICES_QUERYResult;
    '*[_type == "skill"] | order(category asc, order asc){\n  name,\n  category,\n  proficiency,\n  percentage,\n  yearsOfExperience,\n  color\n}': SKILLS_QUERYResult;
    '*[_type == "testimonial" && featured == true] | order(order asc){\n  name,\n  position,\n  company,\n  testimonial,\n  testimonialFr,\n  rating,\n  date,\n  avatar,\n  companyLogo,\n  linkedinUrl\n}': TESTIMONIALS_QUERYResult;
  }
}
